experiment:
  name: upfall_multimodal_hfl
  mode: hfl
  seed: 1337
  rounds: 60
  clients_per_round: 15
  total_clients: 60
  local_epochs: 3
  batch_size: 64
  lr: 1e-3
  optimizer: adam
  device: cuda

data:
  dataset: upfall       # upfall | synthetic
  imu_window_sec: 2.0
  imu_hz: 100
  modalities: [imu, rgb]
  subject_wise_split: true
  train_subject_frac: 0.7
  val_subject_frac: 0.1

model:
  imu_channels: 6
  rgb_feat_dim: 34       # pose keypoints mean coords (17 joints x 2)
  hidden_dim: 128
  fusion: residual_gate  # early | late | residual | residual_gate
  adapters: true
  elm_head: true
  modality_dropout_p: 0.3
  gate_threshold: 0.6

privacy:
  enable_dp: true
  clip_norm: 1.0
  noise_multiplier: 0.7
  target_delta: 1e-5

robust:
  aggregator: trimmed_mean   # fedavg | median | trimmed_mean
  trim_frac: 0.1
  max_update_norm: 5.0

selection:
  enable_pareto: true
  max_clients_per_round: 15

comm:
  quantize_8bit: true
  topk_frac: 0.2
  important_weights: true
  important_ratio: 0.4

semi_supervised:
  enable: true
  pl_threshold: 0.9
  consistency_weight: 0.1

vfl:
  partyA: imu
  partyB: rgb
  split_hidden: 64
  psi_simulation: true

eval:
  lodo: false
  metrics: [accuracy, f1, sensitivity, specificity]
  save_best_by: f1